import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.scss";
import { signOut, useSession } from "next-auth/react";
import channelService, { Channel } from "@/services/channelService";
import { GetServerSideProps } from "next";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]";
import { youtube_v3 } from "googleapis";
import { Paper, Typography } from "@mui/material";

export type HomeProps = {
  channel: youtube_v3.Schema$Channel;
};

export default function Home({ channel }: HomeProps) {
  return (
    <>
      <Head>
        <title>Compiler</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Paper>
        <Typography>Videos uploaded: 12</Typography>
      </Paper>
    </>
  );
}

export const getServerSideProps: GetServerSideProps<HomeProps> = async (
  context
) => {
  let session = await getServerSession(context.req, context.res, authOptions);

  let channel = await channelService.getChannel(session?.account);

  return {
    props: {
      channel,
    },
  };
};
